/*
 *  Copyright 2014 Alexey Andreev.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.teavm.diagnostics;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.Arrays;
import org.teavm.model.*;

/**
 * 
 * @param template
 * 
 * a template of the problem message.
 * 
 * <p> The template may contain placeholders for parameters in the form of
 * <code>{{xN}}</code>, where <code>x</code> is a letter denoting the type of the parameter and <code>N</code> is the index of the parameter in the array returned by {@link #getParams()}.
 * The following parameter types are supported:
 * <ul>
 * <li><code>c</code> - class name</li>
 * <li><code>t</code> - type</li>
 * <li><code>m</code> - method reference</li>
 * <li><code>f</code> - field reference</li>
 * <li><code>l</code> - text location</li>
 * </ul>
 * 
 */
public record Problem(ProblemSeverity severity, Throwable stackTrace, CallLocation location, String template, Object[] params) implements Serializable {

    public Problem(ProblemSeverity severity, CallLocation location, String template, Object[] params) {
        this(severity, new Exception(MessageFormat.format("{0} at {1}", severity, location)), location, template, params);
    }

    public Problem(ProblemSeverity severity, Throwable stackTrace, CallLocation location, String template, Object[] params) {
        this.severity = severity;
        this.stackTrace = stackTrace ;
        this.location = location;
        this.template = template;
        this.params = Arrays.copyOf(params, params.length);
    }

    public ProblemSeverity getSeverity() {
        return severity;
    }

    public CallLocation getLocation() {
        return location;
    }

    /**
     * return the original template string ({@link #template}).
     */
    public String getTemplate() {
        return template;
    }

    public Object[] getParams() {
        return params;
    }

    /**
     * <p> return a human-readable message of the problem, with all parameters substituted.
     * the message is generated by substituting all placeholders in the template with corresponding parameters using the rules as mentioned in {@link #template}.
     */
    public String getText() {
        var b = new DefaultProblemTextConsumer();
        render(b);
        return b.getText();
    }

    /**
     * render the problem message using the provided consumer. The message is generated by substituting all placeholders in the template with corresponding parameters using the rules as mentioned in {@link #template}.
     */
    public void render(ProblemTextConsumer consumer) {
        int index = 0;
        while (index < template.length()) {
            int next = template.indexOf("{{", index);
            if (next < 0) {
                break;
            }
            consumer.append(template.substring(index, next));
            index = parseParameter(consumer, next);
            if (index == next) {
                consumer.append("{{");
                index += 2;
            }
        }
        consumer.append(template.substring(index));
    }

    private int parseParameter(ProblemTextConsumer consumer, int index) {
        int next = index + 2;
        if (next >= template.length()) {
            return index;
        }
        ParamType type;
        switch (Character.toLowerCase(template.charAt(next++))) {
            case 'c':
                type = ParamType.CLASS;
                break;
            case 't':
                type = ParamType.TYPE;
                break;
            case 'm':
                type = ParamType.METHOD;
                break;
            case 'f':
                type = ParamType.FIELD;
                break;
            case 'l':
                type = ParamType.LOCATION;
                break;
            default:
                return index;
        }
        int digitsEnd = skipDigits(next);
        if (digitsEnd == next) {
            return index;
        }
        int paramIndex = Integer.parseInt(template.substring(next, digitsEnd));
        if (paramIndex >= params.length) {
            return index;
        }
        next = digitsEnd;
        if (next + 1 >= template.length() || !template.substring(next, next + 2).equals("}}")) {
            return index;
        }
        Object param = params[paramIndex];
        switch (type) {
            case CLASS:
                if (!(param instanceof String)) {
                    return index;
                }
                consumer.appendClass((String) param);
                break;
            case TYPE:
                if (!(param instanceof ValueType)) {
                    return index;
                }
                consumer.appendType((ValueType) param);
                break;
            case METHOD:
                if (!(param instanceof MethodReference)) {
                    return index;
                }
                consumer.appendMethod((MethodReference) param);
                break;
            case FIELD:
                if (!(param instanceof FieldReference)) {
                    return index;
                }
                consumer.appendField((FieldReference) param);
                break;
            case LOCATION:
                if (!(param instanceof TextLocation)) {
                    return index;
                }
                consumer.appendLocation((TextLocation) param);
                break;
        }
        next += 2;
        return next;
    }

    private int skipDigits(int index) {
        while (index < template.length() && Character.isDigit(template.charAt(index))) {
            ++index;
        }
        return index;
    }

    enum ParamType {
        CLASS,
        TYPE,
        METHOD,
        FIELD,
        LOCATION
    }
}
